//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EYM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string IdentificationNumber { get; set; }
        public string BloodClass { get; set; }
        public string TelephoneNumber { get; set; }
        public string Adress { get; set; }
        public string Gender { get; set; }
        public string Status { get; set; }
        public Nullable<short> authority { get; set; }
    }
}
