//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EYM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RollCall
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime CallTime { get; set; }
        public int LessonID { get; set; }
    
        public virtual Lessons Lessons { get; set; }
        public virtual Students Students { get; set; }
    }
}
