//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EYM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.LessonAndStudent = new HashSet<LessonAndStudent>();
            this.RollCall = new HashSet<RollCall>();
        }
    
        public int StudentID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string IdentificationNumber { get; set; }
        public string BloodClass { get; set; }
        public string TelephoneNumber { get; set; }
        public string Adress { get; set; }
        public Nullable<short> DisabledRatio { get; set; }
        public string DisabledInfo { get; set; }
        public string StudentInfo { get; set; }
        public string SpecialEducation { get; set; }
        public string Gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonAndStudent> LessonAndStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RollCall> RollCall { get; set; }
    }
}
